name: Core Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "pypy-3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Pipx cache for poetry
      uses: actions/cache@v3
      with:
        path: |
          /opt/pipx/venvs/poetry
          /opt/pipx_bin/poetry
        key: pipx-venvs
    - name: Install poetry
      run: |
        pipx install poetry
        pipx list --verbose
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache for poetry venv and tools
      uses: actions/cache@v3
      with:
        path: |
          ./.cache
          ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - run: poetry install --without doc
    - name: Unit tests with pytest
      run: poetry run pytest
    - name: Static typechecking with mypy
      run: poetry run mypy ./zammadoo
    - name: Static code analysis with pylint
      run: |
        poetry run pylint ./zammadoo
